### ISSUE TITLE
Definición

### ISSUE THREAD

**Issue by damiancastelao** [damiancastelao/JugandoConIssues#1]
Esta es la _definición_ de **issue**

**Comment by cristianmoreiraa** [comment]
![image](https://user-images.githubusercontent.com/113538958/227462384-86b530cd-6098-43ae-880d-93bb30662b29.png)

**Comment by NicolasRodriguezSteuerberg** [comment]
Para añadir etiquetas

**Comment by LidierRaccioppe** [comment]
Problema o incoveniente a atender

**Comment by acasella03** [comment]
Un Issue es una nota en un repositorio que trata de llamar la atención sobre un problema.

**Comment by JorgeAmestoy** [comment]
Los issues de github se refieren a dudas o errores para solucionar y aclarar

**Comment by NicolasRodriguezSteuerberg** [comment]
> ![image](https://user-images.githubusercontent.com/113538958/227462384-86b530cd-6098-43ae-880d-93bb30662b29.png)

mal

**Comment by LidierRaccioppe** [comment]
> Esta es la _definición_ de **issue**

Puede estar incomplenta la definición.

**Comment by PPAGabriel** [comment]
Un Issue es una nota en un repositorio que trata de llamar la atención sobre un problema. Puede ser un error a corregir, una petición para añadir una nueva opción o característica, una pregunta para aclarar algún tema que no está correctamente aclarado o muchas otras cosas diferentes.

**Comment by NicolasRodriguezSteuerberg** [comment]
> Un Issue es una nota en un repositorio que trata de llamar la atención sobre un problema. Puede ser un error a corregir, una petición para añadir una nueva opción o característica, una pregunta para aclarar algún tema que no está correctamente aclarado o muchas otras cosas diferentes.

se nota el copy paste

**Comment by JayBGB** [comment]
Un issue en GitHub es una herramienta que se utiliza para realizar un seguimiento de problemas, errores, tareas o solicitudes de funciones en un proyecto de software. Los usuarios pueden crear un issue para informar sobre un problema o sugerir una mejora en el proyecto.

Los issues proporcionan una forma de organizar y gestionar las actividades del proyecto, ya que permiten a los miembros del equipo colaborar en la resolución de problemas y hacer un seguimiento de las tareas pendientes. También permiten a los usuarios informar sobre problemas o solicitar nuevas características de una manera estructurada y transparente, lo que ayuda a los desarrolladores a comprender las necesidades de los usuarios y a mantener la calidad del proyecto.

Los issues pueden contener información detallada sobre el problema o la tarea en cuestión, como una descripción, capturas de pantalla, etiquetas, comentarios y asignaciones a miembros del equipo. Una vez que se resuelve un problema o se completa una tarea, el issue correspondiente puede cerrarse para indicar que se ha resuelto.

**Comment by Miguii-6** [comment]
Damian where are u??

**Comment by damiancastelao** [comment]
> Damian where are u??

I am here

**Comment by JayBGB** [comment]
Un issue en GitHub es una herramienta que se utiliza para realizar un seguimiento de problemas, errores, tareas o solicitudes de funciones en un proyecto de software. Los usuarios pueden crear un issue para informar sobre un problema o sugerir una mejora en el proyecto.

Los issues proporcionan una forma de organizar y gestionar las actividades del proyecto, ya que permiten a los miembros del equipo colaborar en la resolución de problemas y hacer un seguimiento de las tareas pendientes. También permiten a los usuarios informar sobre problemas o solicitar nuevas características de una manera estructurada y transparente, lo que ayuda a los desarrolladores a comprender las necesidades de los usuarios y a mantener la calidad del proyecto.

Los issues pueden contener información detallada sobre el problema o la tarea en cuestión, como una descripción, capturas de pantalla, etiquetas, comentarios y asignaciones a miembros del equipo. Una vez que se resuelve un problema o se completa una tarea, el issue correspondiente puede cerrarse para indicar que se ha resuelto.

**Comment by JorgeAmestoy** [comment]
@acasella03 felices 26 añitos :)

**Comment by damiancastelao** [comment]
Basta de definir!
